# This file was added for TechDocs in Unity Internal Developer Portal http://go/docs-techdocs
# For more information on the configuration below see https://www.mkdocs.org/user-guide/configuration/
site_name: immersive-commerce-walmart-relay
repo_url: https://github.com/Unity-Technologies/immersive-commerce-walmart-relay
repo_name: GitHub
docs_dir: docs
edit_uri: "edit/main/docs/"
strict: true
plugins:
  - techdocs-core
nav:
  - About TechDocs: "index.md"
  - Introduction to immersive-commerce-walmart-relay: "intro.md"
  - Architecture and design: "design.md"
  - Installing for local development: "installation.md"
  - Troubleshooting: "troubleshooting.md"
  - Runbook: "runbook.md"
